#!/bin/sh
cd /tmp/work
magiskboot cpio ramdisk.cpio \
"add 750 twres/c_bg_sub/c_aex/c_about_tile.png /twres/c_bg_sub/c_aex/c_about_tile.png" \
"add 750 twres/c_bg_sub/c_aex/c_circle4.png /twres/c_bg_sub/c_aex/c_circle4.png" \
"add 750 twres/c_bg_sub/c_aex/c_panel_copy_log.png /twres/c_bg_sub/c_aex/c_panel_copy_log.png" \
"add 750 twres/c_bg_sub/c_aex/c_panel_reboot_recovery.png /twres/c_bg_sub/c_aex/c_panel_reboot_recovery.png" \
"add 750 twres/c_bg_sub/c_aex/c_panel_reboot_system.png /twres/c_bg_sub/c_aex/c_panel_reboot_system.png" \
"add 750 twres/c_bg_sub/c_aex/c_panel_wipe_cache.png /twres/c_bg_sub/c_aex/c_panel_wipe_cache.png" \
"add 750 twres/c_bg_sub/c_aex/c_power_menu_bg.png /twres/c_bg_sub/c_aex/c_power_menu_bg.png" \
"add 750 twres/c_bg_sub/c_aex/radio_false.png /twres/c_bg_sub/c_aex/radio_false.png" \
"add 750 twres/c_bg_sub/c_dark/c_about_tile.png /twres/c_bg_sub/c_dark/c_about_tile.png" \
"add 750 twres/c_bg_sub/c_dark/c_circle4.png /twres/c_bg_sub/c_dark/c_circle4.png" \
"add 750 twres/c_bg_sub/c_dark/c_panel_copy_log.png /twres/c_bg_sub/c_dark/c_panel_copy_log.png" \
"add 750 twres/c_bg_sub/c_dark/c_panel_reboot_recovery.png /twres/c_bg_sub/c_dark/c_panel_reboot_recovery.png" \
"add 750 twres/c_bg_sub/c_dark/c_panel_reboot_system.png /twres/c_bg_sub/c_dark/c_panel_reboot_system.png" \
"add 750 twres/c_bg_sub/c_dark/c_panel_wipe_cache.png /twres/c_bg_sub/c_dark/c_panel_wipe_cache.png" \
"add 750 twres/c_bg_sub/c_dark/c_power_menu_bg.png /twres/c_bg_sub/c_dark/c_power_menu_bg.png" \
"add 750 twres/c_bg_sub/c_dark/radio_false.png /twres/c_bg_sub/c_dark/radio_false.png" \
"add 750 twres/c_bg_sub/c_dblue/c_about_tile.png /twres/c_bg_sub/c_dblue/c_about_tile.png" \
"add 750 twres/c_bg_sub/c_dblue/c_circle4.png /twres/c_bg_sub/c_dblue/c_circle4.png" \
"add 750 twres/c_bg_sub/c_dblue/c_panel_copy_log.png /twres/c_bg_sub/c_dblue/c_panel_copy_log.png" \
"add 750 twres/c_bg_sub/c_dblue/c_panel_reboot_recovery.png /twres/c_bg_sub/c_dblue/c_panel_reboot_recovery.png" \
"add 750 twres/c_bg_sub/c_dblue/c_panel_reboot_system.png /twres/c_bg_sub/c_dblue/c_panel_reboot_system.png" \
"add 750 twres/c_bg_sub/c_dblue/c_panel_wipe_cache.png /twres/c_bg_sub/c_dblue/c_panel_wipe_cache.png" \
"add 750 twres/c_bg_sub/c_dblue/c_power_menu_bg.png /twres/c_bg_sub/c_dblue/c_power_menu_bg.png" \
"add 750 twres/c_bg_sub/c_dblue/radio_false.png /twres/c_bg_sub/c_dblue/radio_false.png" \
"add 750 twres/c_bg_sub/c_black/c_about_tile.png /twres/c_bg_sub/c_black/c_about_tile.png" \
"add 750 twres/c_bg_sub/c_black/c_circle4.png /twres/c_bg_sub/c_black/c_circle4.png" \
"add 750 twres/c_bg_sub/c_black/c_panel_copy_log.png /twres/c_bg_sub/c_black/c_panel_copy_log.png" \
"add 750 twres/c_bg_sub/c_black/c_panel_reboot_recovery.png /twres/c_bg_sub/c_black/c_panel_reboot_recovery.png" \
"add 750 twres/c_bg_sub/c_black/c_panel_reboot_system.png /twres/c_bg_sub/c_black/c_panel_reboot_system.png" \
"add 750 twres/c_bg_sub/c_black/c_panel_wipe_cache.png /twres/c_bg_sub/c_black/c_panel_wipe_cache.png" \
"add 750 twres/c_bg_sub/c_black/c_power_menu_bg.png /twres/c_bg_sub/c_black/c_power_menu_bg.png" \
"add 750 twres/c_bg_sub/c_black/radio_false.png /twres/c_bg_sub/c_black/radio_false.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_20.png /twres/c_bg_sub/c_black/c_battery_20.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_30.png /twres/c_bg_sub/c_black/c_battery_30.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_50.png /twres/c_bg_sub/c_black/c_battery_50.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_60.png /twres/c_bg_sub/c_black/c_battery_60.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_80.png /twres/c_bg_sub/c_black/c_battery_80.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_90.png /twres/c_bg_sub/c_black/c_battery_90.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_full.png /twres/c_bg_sub/c_black/c_battery_full.png" \
"add 750 twres/c_bg_sub/c_black/c_battery_low.png /twres/c_bg_sub/c_black/c_battery_low.png" \
"add 750 twres/c_bg_sub/c_white/c_about_tile.png /twres/c_bg_sub/c_white/c_about_tile.png" \
"add 750 twres/c_bg_sub/c_white/c_circle4.png /twres/c_bg_sub/c_white/c_circle4.png" \
"add 750 twres/c_bg_sub/c_white/c_panel_copy_log.png /twres/c_bg_sub/c_white/c_panel_copy_log.png" \
"add 750 twres/c_bg_sub/c_white/c_panel_reboot_recovery.png /twres/c_bg_sub/c_white/c_panel_reboot_recovery.png" \
"add 750 twres/c_bg_sub/c_white/c_panel_reboot_system.png /twres/c_bg_sub/c_white/c_panel_reboot_system.png" \
"add 750 twres/c_bg_sub/c_white/c_panel_wipe_cache.png /twres/c_bg_sub/c_white/c_panel_wipe_cache.png" \
"add 750 twres/c_bg_sub/c_white/c_power_menu_bg.png /twres/c_bg_sub/c_white/c_power_menu_bg.png" \
"add 750 twres/c_bg_sub/c_white/radio_false.png /twres/c_bg_sub/c_white/radio_false.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_20.png /twres/c_bg_sub/c_white/c_battery_20.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_30.png /twres/c_bg_sub/c_white/c_battery_30.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_50.png /twres/c_bg_sub/c_white/c_battery_50.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_60.png /twres/c_bg_sub/c_white/c_battery_60.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_80.png /twres/c_bg_sub/c_white/c_battery_80.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_90.png /twres/c_bg_sub/c_white/c_battery_90.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_full.png /twres/c_bg_sub/c_white/c_battery_full.png" \
"add 750 twres/c_bg_sub/c_white/c_battery_low.png /twres/c_bg_sub/c_white/c_battery_low.png" \
"add 750 twres/c_nav_sub/c_blue/back.png /twres/c_nav_sub/c_blue/back.png" \
"add 750 twres/c_nav_sub/c_blue/console.png /twres/c_nav_sub/c_blue/console.png" \
"add 750 twres/c_nav_sub/c_blue/home.png /twres/c_nav_sub/c_blue/home.png" \
"add 750 twres/c_nav_sub/c_brown/back.png /twres/c_nav_sub/c_brown/back.png" \
"add 750 twres/c_nav_sub/c_brown/console.png /twres/c_nav_sub/c_brown/console.png" \
"add 750 twres/c_nav_sub/c_brown/home.png /twres/c_nav_sub/c_brown/home.png" \
"add 750 twres/c_nav_sub/c_cyan/back.png /twres/c_nav_sub/c_cyan/back.png" \
"add 750 twres/c_nav_sub/c_cyan/console.png /twres/c_nav_sub/c_cyan/console.png" \
"add 750 twres/c_nav_sub/c_cyan/home.png /twres/c_nav_sub/c_cyan/home.png" \
"add 750 twres/c_nav_sub/c_dark/back.png /twres/c_nav_sub/c_dark/back.png" \
"add 750 twres/c_nav_sub/c_dark/console.png /twres/c_nav_sub/c_dark/console.png" \
"add 750 twres/c_nav_sub/c_dark/home.png /twres/c_nav_sub/c_dark/home.png" \
"add 750 twres/c_nav_sub/c_green/back.png /twres/c_nav_sub/c_green/back.png" \
"add 750 twres/c_nav_sub/c_green/console.png /twres/c_nav_sub/c_green/console.png" \
"add 750 twres/c_nav_sub/c_green/home.png /twres/c_nav_sub/c_green/home.png" \
"add 750 twres/c_nav_sub/c_indigo/back.png /twres/c_nav_sub/c_indigo/back.png" \
"add 750 twres/c_nav_sub/c_indigo/console.png /twres/c_nav_sub/c_indigo/console.png" \
"add 750 twres/c_nav_sub/c_indigo/home.png /twres/c_nav_sub/c_indigo/home.png" \
"add 750 twres/c_nav_sub/c_lred/back.png /twres/c_nav_sub/c_lred/back.png" \
"add 750 twres/c_nav_sub/c_lred/console.png /twres/c_nav_sub/c_lred/console.png" \
"add 750 twres/c_nav_sub/c_lred/home.png /twres/c_nav_sub/c_lred/home.png" \
"add 750 twres/c_nav_sub/c_orange/back.png /twres/c_nav_sub/c_orange/back.png" \
"add 750 twres/c_nav_sub/c_orange/console.png /twres/c_nav_sub/c_orange/console.png" \
"add 750 twres/c_nav_sub/c_orange/home.png /twres/c_nav_sub/c_orange/home.png" \
"add 750 twres/c_nav_sub/c_pink/back.png /twres/c_nav_sub/c_pink/back.png" \
"add 750 twres/c_nav_sub/c_pink/console.png /twres/c_nav_sub/c_pink/console.png" \
"add 750 twres/c_nav_sub/c_pink/home.png /twres/c_nav_sub/c_pink/home.png" \
"add 750 twres/c_nav_sub/c_purple/back.png /twres/c_nav_sub/c_purple/back.png" \
"add 750 twres/c_nav_sub/c_purple/console.png /twres/c_nav_sub/c_purple/console.png" \
"add 750 twres/c_nav_sub/c_purple/home.png /twres/c_nav_sub/c_purple/home.png" \
"add 750 twres/c_nav_sub/c_red/back.png /twres/c_nav_sub/c_red/back.png" \
"add 750 twres/c_nav_sub/c_red/console.png /twres/c_nav_sub/c_red/console.png" \
"add 750 twres/c_nav_sub/c_red/home.png /twres/c_nav_sub/c_red/home.png" \
"add 750 twres/c_nav_sub/c_rpink/back.png /twres/c_nav_sub/c_rpink/back.png" \
"add 750 twres/c_nav_sub/c_rpink/console.png /twres/c_nav_sub/c_rpink/console.png" \
"add 750 twres/c_nav_sub/c_rpink/home.png /twres/c_nav_sub/c_rpink/home.png" \
"add 750 twres/c_nav_sub/c_teal/back.png /twres/c_nav_sub/c_teal/back.png" \
"add 750 twres/c_nav_sub/c_teal/console.png /twres/c_nav_sub/c_teal/console.png" \
"add 750 twres/c_nav_sub/c_teal/home.png /twres/c_nav_sub/c_teal/home.png" \
"add 750 twres/c_nav_sub/c_white/back.png /twres/c_nav_sub/c_white/back.png" \
"add 750 twres/c_nav_sub/c_white/console.png /twres/c_nav_sub/c_white/console.png" \
"add 750 twres/c_nav_sub/c_white/home.png /twres/c_nav_sub/c_white/home.png" \
"add 750 twres/c_nav_sub/c_yellow/back.png /twres/c_nav_sub/c_yellow/back.png" \
"add 750 twres/c_nav_sub/c_yellow/console.png /twres/c_nav_sub/c_yellow/console.png" \
"add 750 twres/c_nav_sub/c_yellow/home.png /twres/c_nav_sub/c_yellow/home.png" \
"add 750 twres/images/backspace.png /twres/images/backspace.png" \
"add 750 twres/images/backup.png /twres/images/backup.png" \
"add 750 twres/images/c_3dot_action.png /twres/images/c_3dot_action.png" \
"add 750 twres/images/c_advanced.png /twres/images/c_advanced.png" \
"add 750 twres/images/c_download_mode.png /twres/images/c_download_mode.png" \
"add 750 twres/images/c_edl_mode.png /twres/images/c_edl_mode.png" \
"add 750 twres/images/c_epicxsort.png /twres/images/c_epicxsort.png" \
"add 750 twres/images/c_dateSort.png /twres/images/c_dateSort.png" \
"add 750 twres/images/c_file_back.png /twres/images/c_file_back.png" \
"add 750 twres/images/c_line.png /twres/images/c_line.png" \
"add 750 twres/images/c_menu.png /twres/images/c_menu.png" \
"add 750 twres/images/c_misc_panel.png /twres/images/c_misc_panel.png" \
"add 750 twres/images/c_ok.png /twres/images/c_ok.png" \
"add 750 twres/images/c_power_off.png /twres/images/c_power_off.png" \
"add 750 twres/images/c_reboot_to_bootloader.png /twres/images/c_reboot_to_bootloader.png" \
"add 750 twres/images/c_reboot_to_recovery.png /twres/images/c_reboot_to_recovery.png" \
"add 750 twres/images/c_reboot_to_system.png /twres/images/c_reboot_to_system.png" \
"add 750 twres/images/checkbox_false.png /twres/images/checkbox_false.png" \
"add 750 twres/images/checkbox_true.png /twres/images/checkbox_true.png" \
"add 750 twres/images/enter.png /twres/images/enter.png" \
"add 750 twres/images/file.png /twres/images/file.png" \
"add 750 twres/images/folder.png /twres/images/folder.png" \
"add 750 twres/images/handle.png /twres/images/handle.png" \
"add 750 twres/images/shift.png /twres/images/shift.png" \
"add 750 twres/images/shift_fill.png /twres/images/shift_fill.png" \
"add 750 twres/images/space.png /twres/images/space.png" \
"add 750 twres/images/c_battery_20.png /twres/images/c_battery_20.png" \
"add 750 twres/images/c_battery_30.png /twres/images/c_battery_30.png" \
"add 750 twres/images/c_battery_50.png /twres/images/c_battery_50.png" \
"add 750 twres/images/c_battery_60.png /twres/images/c_battery_60.png" \
"add 750 twres/images/c_battery_80.png /twres/images/c_battery_80.png" \
"add 750 twres/images/c_battery_90.png /twres/images/c_battery_90.png" \
"add 750 twres/images/c_battery_full.png /twres/images/c_battery_full.png" \
"add 750 twres/images/c_battery_low.png /twres/images/c_battery_low.png" \
"add 750 twres/images/c_about_tile.png /twres/images/c_about_tile.png" \
"add 750 twres/images/c_circle4.png /twres/images/c_circle4.png" \
"add 750 twres/images/c_panel_copy_log.png /twres/images/c_panel_copy_log.png" \
"add 750 twres/images/c_panel_reboot_recovery.png /twres/images/c_panel_reboot_recovery.png" \
"add 750 twres/images/c_panel_reboot_system.png /twres/images/c_panel_reboot_system.png" \
"add 750 twres/images/c_panel_wipe_cache.png /twres/images/c_panel_wipe_cache.png" \
"add 750 twres/images/c_power_menu_bg.png /twres/images/c_power_menu_bg.png" \
"add 750 twres/images/c_reload.png /twres/images/c_reload.png" \
"add 750 twres/images/radio_false.png /twres/images/radio_false.png" \
"add 750 twres/images/radio_true.png /twres/images/radio_true.png" \
"add 750 twres/images/c_usersRadioOn.png /twres/images/c_usersRadioOn.png" \
"add 750 twres/images/c_usersRadioOff.png /twres/images/c_usersRadioOff.png" \
"add 750 twres/images/kb_show.png /twres/images/kb_show.png" \
"add 750 twres/images/back.png /twres/images/back.png" \
"add 750 twres/images/console.png /twres/images/console.png" \
"add 750 twres/images/home.png /twres/images/home.png" \
"add 750 twres/images/c_adb.png /twres/images/c_adb.png" \
"add 750 twres/images/c_dashboard_about.png /twres/images/c_dashboard_about.png" \
"add 750 twres/images/c_dashboard_addon.png /twres/images/c_dashboard_addon.png" \
"add 750 twres/images/c_dashboard_advanced.png /twres/images/c_dashboard_advanced.png" \
"add 750 twres/images/c_dashboard_backup.png /twres/images/c_dashboard_backup.png" \
"add 750 twres/images/c_dashboard_filemanager.png /twres/images/c_dashboard_filemanager.png" \
"add 750 twres/images/c_dashboard_flash.png /twres/images/c_dashboard_flash.png" \
"add 750 twres/images/c_dashboard_lang.png /twres/images/c_dashboard_lang.png" \
"add 750 twres/images/c_dashboard_lock.png /twres/images/c_dashboard_lock.png" \
"add 750 twres/images/c_dashboard_magisk.png /twres/images/c_dashboard_magisk.png" \
"add 750 twres/images/c_dashboard_mount.png /twres/images/c_dashboard_mount.png" \
"add 750 twres/images/c_dashboard_reboot.png /twres/images/c_dashboard_reboot.png" \
"add 750 twres/images/c_dashboard_restore.png /twres/images/c_dashboard_restore.png" \
"add 750 twres/images/c_dashboard_settings.png /twres/images/c_dashboard_settings.png" \
"add 750 twres/images/c_dashboard_terminal.png /twres/images/c_dashboard_terminal.png" \
"add 750 twres/images/c_dashboard_wipe.png /twres/images/c_dashboard_wipe.png" \
"add 750 twres/images/c_dashboard_userFbe.png /twres/images/c_dashboard_userFbe.png" \
"add 750 twres/images/c_log.png /twres/images/c_log.png" \
"add 750 twres/images/c_mod.png /twres/images/c_mod.png" \
"add 750 twres/images/c_sd_part.png /twres/images/c_sd_part.png" \
"add 750 twres/images/c_selinux.png /twres/images/c_selinux.png" \
"add 750 twres/images/c_rounded_1.png /twres/images/c_rounded_1.png" \
"add 750 twres/images/c_rounded_2.png /twres/images/c_rounded_2.png" \
"add 750 twres/images/c_rounded_3.png /twres/images/c_rounded_3.png" \
"add 750 twres/images/c_rounded_4.png /twres/images/c_rounded_4.png" \
"add 750 twres/images/c_clear_input.png /twres/images/c_clear_input.png" \
"add 750 twres/images/kb_arrow_down.png /twres/images/kb_arrow_down.png" \
"add 750 twres/images/kb_arrow_left.png /twres/images/kb_arrow_left.png" \
"add 750 twres/images/kb_arrow_right.png /twres/images/kb_arrow_right.png" \
"add 750 twres/images/kb_arrow_up.png /twres/images/kb_arrow_up.png" \
"add 750 twres/images/c_plus.png /twres/images/c_plus.png" \
"add 750 twres/images/c_minus.png /twres/images/c_minus.png" \
"add 750 twres/images/c_copy.png /twres/images/c_copy.png" \
"add 750 twres/images/c_cut.png /twres/images/c_cut.png" \
"add 750 twres/images/c_file_delete2.png /twres/images/c_file_delete2.png" \
"add 750 twres/images/c_ch755.png /twres/images/c_ch755.png" \
"add 750 twres/images/c_chmod.png /twres/images/c_chmod.png" \
"add 750 twres/images/c_paste.png /twres/images/c_paste.png" \
"add 750 twres/images/c_rename.png /twres/images/c_rename.png" \
"add 750 twres/images/c_splash_bg.png /twres/images/c_splash_bg.png" \
"add 750 twres/images/c_factory_reset.png /twres/images/c_factory_reset.png" \
"add 750 twres/images/c_applyCustomTheme.png /twres/images/c_applyCustomTheme.png" \
"add 750 twres/images/c_displayTxt.png /twres/images/c_displayTxt.png" \
"add 750 twres/images/c_editTxt.png /twres/images/c_editTxt.png" \
"add 750 twres/images/c_removeLine.png /twres/images/c_removeLine.png" \
"add 750 twres/bg_res.xml /twres/bg_res.xml" \
"add 750 twres/c_status_bar_h.xml /twres/c_status_bar_h.xml" \
"add 750 twres/notch_handled_var.xml /twres/notch_handled_var.xml" \
"add 750 twres/txt_res.xml /twres/txt_res.xml" \
"add 750 twres/slts /twres/slts"
