#!/sbin/sh
# Magisk Manager for Recovery Mode (mm)
# Copyright (C) 2017-2019, VR25 @ xda-developers
# License: GPLv3+
# We are adding this file in Skyhawk Recovery Project to extend the Recovery Feature.
# Thank You VR25.
touch /data/cache/.disable_magisk
touch /cache/.disable_magisk
